### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by saurbhc** [saurbhc/awslack#2]
# TODO

* [x] add pre-commit
* [x] add poetry
* [ ] add tests
* [ ] install module and upload to pypi
* [ ] read conf from a conf file
* [ ] create 2 entry_points for build & deploy
